apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/external
        pathType: Prefix
        backend:
          service:
            name: gi-external-bridge
            port:
              number: 3001
      - path: /api/v3
        pathType: Prefix
        backend:
          service:
            name: gi-web-bridge
            port:
              number: 3002
      - path: /api/common
        pathType: Prefix
        backend:
          service:
            name: gi-common-service
            port:
              number: 3003
      - path: /api/v2
        pathType: Prefix
        backend:
          service:
            name: grip-client-backend
            port:
              number: 4000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gi-client-web
            port:
              number: 8081
      - path: /payment-processing
        pathType: Prefix
        backend:
          service:
            name: gi-client-web
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gi-client-static
            port:
              number: 3000